# Generated by Django 5.2.7 on 2025-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reign_start', models.DateField()),
                ('reign_end', models.DateField(blank=True, null=True)),
                ('years_reigned', models.CharField(max_length=100)),
                ('is_good', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'King',
                'verbose_name_plural': 'Kings',
            },
        ),
    ]
