# Generated by Django 5.2.7 on 2025-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='king',
            name='reign_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='king',
            name='reign_start',
            field=models.IntegerField(),
        ),
    ]
