# Generated by Django 5.2.7 on 2025-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prophet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('books', models.TextField(help_text='Comma-separated list of books attributed to the prophet')),
            ],
            options={
                'verbose_name': 'Prophet',
                'verbose_name_plural': 'Prophets',
            },
        ),
    ]
