# Generated by Django 5.2.7 on 2025-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prophet',
            name='birth_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prophet',
            name='death_year',
            field=models.CharField(default='7th century BC', max_length=100),
            preserve_default=False,
        ),
    ]
